'use strict';
// A generic config file that can be (re-)used by webpack and gulpfile config

// For your configuration pleasure
// * NO TRAILING SLASH on directories
// * Use forward slashes (/) even for Windows paths
// * Best to keep paths relative to project root
var config = {
  // Name of our app
  title: "TypeScript-Flux App",

  // Where builds go (generally)
  distDir: "dist",

  // Where our source code can be found
  srcDir: "src",

  // Where our non-source assets can be found
  assetsDir: "assets",

  // Primary entry point for webpack
  entry: "src/index.js",

  // Path to a Bower components listing file (this should be required by the 
  // primary entry point)
  vendorIndex: "src/bower_reqs.js",

  // A blueimp template for HTML pages generated by HtmlWebpackPlugin
  templatePath: "src/template.html",

  // Path to favicon
  // TODO: wider support for mobile app icons, etc.
  faviconPath: "./assets/favicon.ico",

  // Browser options for autoprefixer -- see 
  // https://github.com/passy/autoprefixer-loader for syntax
  autoprefixerOpts: "",

  // Port for dev server
  devPort: 8000
};

// Infer Bower directory
var bowerRc;
try {
  bowerRc = require("./.bowerrc");
} catch (err) {
  // Do nothing -> absence of .bowerrc means we default to bower_components
}
if (bowerRc && bowerRc.path) {
  config.bowerDir = bowerRc.path;
} else {
  config.bowerDir = "bower_components";
}

// Other 
module.exports = config;